# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtWidgets


class UiProgress(object):
    def setupUi(self, w_vk_upload):
        w_vk_upload.setObjectName("w_vk_upload")
        w_vk_upload.setWindowModality(QtCore.Qt.ApplicationModal)
        w_vk_upload.resize(440, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(w_vk_upload.sizePolicy().hasHeightForWidth())
        w_vk_upload.setSizePolicy(sizePolicy)
        w_vk_upload.setMinimumSize(QtCore.QSize(440, 100))
        w_vk_upload.setMaximumSize(QtCore.QSize(440, 100))
        w_vk_upload.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        w_vk_upload.setModal(True)
        self.progressBar = QtWidgets.QProgressBar(w_vk_upload)
        self.progressBar.setGeometry(QtCore.QRect(20, 40, 400, 25))
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(w_vk_upload)
        self.label.setGeometry(QtCore.QRect(20, 10, 400, 25))
        self.label.setText("")
        self.label.setObjectName("label")
        self.error_label = QtWidgets.QLabel(w_vk_upload)
        self.error_label.setGeometry(QtCore.QRect(20, 70, 400, 25))
        self.error_label.setText("")
        self.error_label.setObjectName("err_label")

        self.retranslateUi(w_vk_upload)
        QtCore.QMetaObject.connectSlotsByName(w_vk_upload)

    def retranslateUi(self, w_vk_upload):
        _translate = QtCore.QCoreApplication.translate
        w_vk_upload.setWindowTitle(_translate("w_vk_upload", "Выгрузка товаров в ВК"))
